# Loads default set of integrations. Do not remove.
default_config:

logger:
  default: info
  logs:
    custom_components.auto_backup: debug

backup:
# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy:
