default_config:

logger:
  default: info
  logs:
    custom_components.auto_backup: debug

# If you need to debug uncomment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy:

automation: !include automations.yaml
